name: event_management
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  permission_handler: ^10.2.0
  path_provider: ^2.1.4
  flutter_sound: ^9.16.0
  shared_preferences: ^2.3.2
  gallery_saver: ^2.3.2
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/events_data.json
    - assets/event_pic1.png
    - assets/event_pic2.png
    - assets/event_pic3.png
  uses-material-design: true

#Launcher
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/image.png"
  min_sdk_android: 21

#Flutter Native Splash
flutter_native_splash:
  color: "#ffffff"
  image: assets/image.png
  ios: true
  android: true
